### ISSUE TITLE
Kalau dibuka di mobile tampilannya ancur

### ISSUE THREAD

**Issue by taufika** [taufika/cari-tiket-kereta#3]
Cobain aja deh

**Comment by sembiringmonika** [comment]
maksudnya buka github di mobile?

**Comment by taufika** [comment]
bukan atuh, kalau si appnya dibuka di mobile tampilannya ancur. http://cari-tiket-kereta.firebaseapp.com

**Comment by sembiringmonika** [comment]
sek bntr ak cek app nya di mobile.

**Comment by sembiringmonika** [comment]
ya juga kalo di browser hp jd ga seperti aslinya.
bentar, itu yg namanya responsive ya fik, kalo bisa di desktop trus kalo pake hp jg ttp bagus?

**Comment by sembiringmonika** [comment]
![whatsapp image 2016-09-30 at 15 11 14](https://cloud.githubusercontent.com/assets/21377614/19032097/1126b2cc-8982-11e6-8723-0312c93a0535.jpeg)

**Comment by sembiringmonika** [comment]
lah knpa ini masih jd bug lagi?
